[tasks.default]
description = "Default task points to the development testing flow"
alias = "test"

[tasks.build]
command = "cargo"
args = [
	"build", "--release", "--manifest-path", "../nask-rs/Cargo.toml"
]

[tasks.post-build]
dependencies = [
 "build", "generate", "to_bin"
]

[tasks.generate]
script = [
"../nask-rs/target/release/nask-rs < ipl.nas > ipl.tmp",
]

[tasks.to_bin]
script = [
"printf \"%b\" `cat ipl.tmp` > ipl.bin",
"cat ipl.bin tail.bin > helloos.img"
]

[tasks.to_hex]
script = [
"xxd ipl.bin > ipl.hex"
]

[tasks.diff]
script = [
"diff ipl.hex mihon.hex"
]

[tasks.test]
dependencies = [
"build",
"post-build",
"to_hex",
"diff"
]


[tasks.rm]
command = "rm"
args = [
	"-f", "ipl.tmp", "ipl.bin", "helloos.img", "ipl.hex"
]


[tasks.clean]
args = [
	"clean", "--manifest-path", "../nask-rs/Cargo.toml"
]
dependencies = ["rm"]

[tasks.cp]
script = [
	"cp helloos.img ../z_tools/qemu/fdimage0.bin"
]

[tasks.run]
command = "cargo"
args = [
	"make", "run", "--makefile", "--cwd", "../z_tools/qemu"
]
dependencies = ["build", "cp"]

